name: Use Secret Example

on:
  push:

jobs:
  use-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print confirmation (without leaking secret)
        run: echo "The secret is \${{ secrets.SECRET }}"
        shell: bash
